version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: task-tracker-db
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  backend:
    build: ./backend
    container_name: task-tracker-backend
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URL=mongodb://database:27017/taskdb
    depends_on:
      - database

  frontend:
    image: node:20-alpine
    container_name: task-tracker-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "tail -f /dev/null"
    ports:
      - "5173:5173"

volumes:
  dbdata: