version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: task-tracker-db
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  backend:
    build: ./backend
    container_name: task-tracker-backend
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URL=mongodb://database:27017/taskdb
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: task-tracker-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  dbdata: