%%{init: {'theme': 'base', 'themeVariables': {'primaryTextColor': '#000', 'secondaryTextColor': '#000'}}}%%
flowchart TB

U([User<br/>Korzysta z aplikacji przy użyciu przeglądarki])

subgraph Frontend Layer
    FE[React + Vite Frontend<br/>Renderuje UI i wysyła zapytania REST komunikując się z BE<br/><b>Port 5173</b>]
end

subgraph Backend Layer
    BE[Node.js Express API<br/>Warstwa logiczna aplikacji<br/><b>Port 3000</b>]
end

subgraph Data Layer
    DB[(Azure Cosmos DB<br/>Przechowuje dane użytkowników i zadania w formie dokumentów NoSQL)]
end

U -- HTTPS --> FE
FE -- REST API --> BE
BE -- NoSQL --> DB

style U fill:#E8EAF6, stroke:#3F5185, stroke-width:2px,color:#000
style FE fill:#EDE7F6, stroke:#3949AB, stroke-width:2px,color:#000
style BE fill:#F3E5F5, stroke:#5635B1, stroke-width:2px,color:#000
style DB fill:#E1F5FE, stroke:#6A1B9A, stroke-width:2px,color:#000